# Project identification
sonar.projectKey=App-Incide
sonar.projectName=App Incide
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
	
# Directorios a analizar
sonar.sources=lib
sonar.tests=test

# Encoding of the source code. Default is default system encoding.
sonar.sourceEncoding=UTF-8

# Ruta del reporte de cobertura generado por Flutter
sonar.flutter.coverage.reportPaths=coverage/lcov.info

# Excluir archivos autogenerados del análisis
sonar.exclusions=**/*.g.dart, **/*.freezed.dart, test/mocks.mocks.dart

# Excluye del cálculo de COBERTURA los módulos que no son de tu jurisdicción (Cliente, UI pura, etc.)
sonar.coverage.exclusions=lib/features/client/**, lib/features/shared/**, lib/features/location/**, lib/**/*.g.dart, lib/**/*.freezed.dart, lib/**/screens/**, lib/**/widgets/**, lib/**/mock_*.dart, lib/core/constants/**, lib/core/network/api_config.dart
# Analyzer mode
# Can be:
# - DETECT (attempt to detect automatically) - default
# - MANUAL (an existing report needs to be provided)
# - FLUTTER (flutter analyze)
# - DART (dart analyze)
# - DARTANALYZER (dartanalyzer)
# sonar.dart.analyzer.mode= 

# Allows reuse of an existing analyzer report when mode is MANUAL
# sonar.dart.analyzer.report.path=

# Analyzer report output mode
# Can be:
# - DETECT (attempt to detect automatically, requires Dart SDK on the PATH) - default
# - MACHINE (a new machine readable output that is available for Dart 2.12+)
# - LEGACY (attempts to parse human readable output from dart/flutter) - default
# sonar.dart.analyzer.report.mode= 